### ISSUE TITLE
"correct_preds" function

### ISSUE THREAD

**Issue by Lilyo** [SchroeterJulien/2020-ICML-UDL-Workshop-Robust-Temporal-Point-Event-Localization#2]
Hi  @SchroeterJulien , I am curious about (1)why you choice event[5] and event[0]? (2)why you choice 30? in below line
https://github.com/SchroeterJulien/2020-ICML-UDL-Workshop-Robust-Temporal-Point-Event-Localization/blob/d5b0ae57b5c093af6269b8778790f9edd0f487ef/4_1_GolfSequencingExperiment/util.py#L34

Looking forward to your reply!

**Comment by SchroeterJulien** [comment]
For the video event detection experiment, we replicate the experiment from McNally [1] and simply replace their loss function with ours. Thus, all other elements of the experiment are identical to their original implementation (https://github.com/wmcnally/golfdb) to allow for maximum comparability and fairness in the evaluation. You can refer to the bottom right of page 4 in their paper (https://arxiv.org/pdf/1903.06528.pdf) for a explanation about the rational behind this choice of tolerance.



[1] McNally, W., Vats, K., Pinto, T., Dulhanty, C., McPhee, J. and Wong, A., 2019. Golfdb: A video database for golf swing sequencing. In CVPR Workshops.

**Comment by Lilyo** [comment]
Close for now
